spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  cors:
    allowed-origin-patterns: ${APP_CORS_ALLOWED_ORIGIN_PATTERNS}
  request-log:
    enabled: ${APP_REQUEST_LOG_ENABLED:true}

logging:
  level:
    root: INFO
    com.pm: INFO
  file:
    path: ${LOG_PATH:./logs}
